kind: Service
apiVersion: v1
metadata:
  name: flowlogs-ingestor-internal
  namespace: datahangar-stack
spec:
  selector:
    app: nfacctd
  ports:
  - name: flowlogs
    protocol: UDP
    port: 2055
    targetPort: 2055
  - name: bgp
    protocol: TCP
    port: 179
    targetPort: 179
  type: ClusterIP
  sessionAffinity: ClientIP
---
kind: Service
apiVersion: v1
metadata:
  name: flowlogs-ingestor
  namespace: datahangar-stack
  annotations:
    service.cilium.io/affinity: "local"
spec:
  selector:
    app: nfacctd
  ports:
  - name: flowlogs
    protocol: UDP
    port: 2055
    targetPort: 2055
  - name: bgp
    protocol: TCP
    port: 179
    targetPort: 179
  type: LoadBalancer
  externalTrafficPolicy: Local #Do not SNAT to the service!
  sessionAffinity: ClientIP
